-- Zieltabelle: MDP01_DISCOVERABLE_LAYER.UZMS01_TARF_ASYLGS_ART_TX_HISTORY
-- Generiert beim Job-Erstellen (Job ID: 34)

CREATE SET TABLE MDP01_DISCOVERABLE_LAYER.UZMS01_TARF_ASYLGS_ART_TX_HISTORY            (                UZMS01_TARF_ASYLGS_ART_TX_SK BIGINT NOT NULL, KEYCD VARCHAR(16), LANG_CD VARCHAR(8), TXT VARCHAR(240), RECORD_HASH BYTE(20), VALID_FROM TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), VALID_TO TIMESTAMP(6), IS_CURRENT CHAR(1) CHARACTER SET UNICODE DEFAULT 'Y', CREATED_TIMESTAMP TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), LAST_UPDATED_TIMESTAMP TIMESTAMP(6), CREATED_BY VARCHAR(128) CHARACTER SET UNICODE DEFAULT USER, LAST_UPDATED_BY VARCHAR(128) CHARACTER SET UNICODE            )            PRIMARY INDEX (UZMS01_TARF_ASYLGS_ART_TX_SK, VALID_FROM);
